trigger:
- master

pool:
  name: Master  # Ensure this matches your actual agent pool name

steps:
- script: |
    echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME)"
  displayName: 'Set JAVA_HOME environment variable'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkUserInputPath: '$(JAVA_HOME)'  # Explicitly use the path to your JDK installation
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    SourceFolder: '/Notorious/Azure/myagent/_work/1/a'
    Contents: '**/*.war'
    TargetFolder: '/Notorious/Azure/myagent/_work/1/s'


