trigger:
- master

pool:
  name: Master  # Ensure this matches your actual agent pool name

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11.x'  # This ensures JDK 11 is used
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'  # This option assumes that the JDK is already installed

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
