trigger:
- master

pool:
  name: Master  # Ensure this matches your actual agent pool name

steps:
- script: |
    echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME)"
  displayName: 'Set JAVA_HOME environment variable'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkUserInputPath: '$(JAVA_HOME)'  # Use the path to your JDK installation
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
